inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 180

Style/AsciiIdentifiers:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'

Style/AsciiComments:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'

Style/VariableName:
  Exclude:
    - 'lib/**/*'

Style/ClassVars:
  Exclude:
    - 'lib/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'lib/kantox/chronoscope/generic.rb'

Style/SpecialGlobalVars:
  Exclude:
    - 'lib/**/*'
