general:
  handler: 'Kantox::Chronoscope::Generic'
  enable: true

options:
  silent: true

lang: :en

i18n:
  en:
    name: method
    times: times
    average: average
    total: total
  ru:
    name: метод
    times: раз
    average: среднее
    total: всего
